# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-18 06:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170218_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 18, 6, 44, 19, 604472, tzinfo=utc)),
        ),
    ]
