# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 05:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170218_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubmanager',
            name='hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.CommunityHub'),
        ),
        migrations.AlterField(
            model_name='innovator',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Innovation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 19, 5, 49, 20, 199230, tzinfo=utc)),
        ),
    ]
