# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 09:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20170220_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key_expires',
            field=models.DateTimeField(default=datetime.timedelta(1)),
        ),
    ]
