# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20170223_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='/static/img/user-placeholder.png', upload_to='static/profile_images'),
        ),
    ]
