# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20170223_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovator',
            name='has_startup',
            field=models.BooleanField(default=False),
        ),
    ]
