# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_innovator_has_startup'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubmanager',
            name='has_hub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investor',
            name='has_company',
            field=models.BooleanField(default=False),
        ),
    ]
