# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20170222_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key_expires',
            field=models.DateTimeField(default=b'2017-02-23 09:27:05.749218+00:00'),
        ),
    ]
