# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20170228_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovator',
            name='team',
        ),
    ]
