# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 09:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20170222_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 23, 9, 31, 15, 61347)),
        ),
    ]
