# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_innovator_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubmanager',
            name='hub',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='company',
        ),
    ]
