# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 14:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20170306_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 6, 14, 46, 23, 843629, tzinfo=utc)),
        ),
    ]
