# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 11:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20170306_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hubmanager',
            options={'verbose_name': 'Hub Manager', 'verbose_name_plural': 'Hub Managers'},
        ),
        migrations.AlterModelOptions(
            name='innovator',
            options={'verbose_name': 'Innovator', 'verbose_name_plural': 'Innovators'},
        ),
        migrations.AlterModelOptions(
            name='investor',
            options={'verbose_name': 'Investor', 'verbose_name_plural': 'Investors'},
        ),
        migrations.AlterModelOptions(
            name='mentor',
            options={'verbose_name': 'Mentor', 'verbose_name_plural': 'Mentors'},
        ),
        migrations.AlterModelOptions(
            name='programmanager',
            options={'verbose_name': 'Program Manager', 'verbose_name_plural': 'Program Managers'},
        ),
        migrations.AlterField(
            model_name='user',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 11, 51, 31, 697008, tzinfo=utc)),
        ),
    ]
