# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 15:23
from __future__ import unicode_literals

import cloudinary.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20170320_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='resume',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='user',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 20, 15, 23, 36, 51521, tzinfo=utc)),
        ),
    ]
