# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 06:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20170411_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 11, 6, 21, 1, 974388, tzinfo=utc)),
        ),
    ]
