# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityHub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(blank=True, max_length=200)),
                ('hub_focus', models.TextField(blank=True)),
                ('preferred_industries', models.CharField(blank=True, max_length=200)),
                ('investment_stage', models.CharField(blank=True, max_length=200)),
                ('support_type', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('logo', models.FileField(blank=True, upload_to='static/logos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Innovation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, max_length=1)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('service_pic', models.ImageField(blank=True, upload_to='static/service_pics/%Y/%m/%d/')),
                ('service_videos', models.TextField(blank=True)),
                ('sectors', models.TextField(blank=True)),
                ('other_sectors', models.CharField(blank=True, max_length=30)),
                ('challenge_to_solve', models.TextField(blank=True)),
                ('challenge_faced', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='static/logos/%Y/%m/%d')),
                ('target_customers', models.TextField(blank=True)),
                ('market_size', models.TextField(blank=True)),
                ('customer_lessons', models.TextField(blank=True)),
                ('acquisition_plan', models.TextField(blank=True)),
                ('potential_competitors', models.TextField(blank=True)),
                ('competitive_advantage', models.TextField(blank=True)),
                ('business_differentiator', models.TextField(blank=True)),
                ('major_wrongs', models.TextField(blank=True)),
                ('revenue', models.TextField(blank=True)),
                ('monthly_costs', models.FileField(blank=True, upload_to='static/uploads/%Y/%m/%d/')),
                ('annual_costs', models.FileField(blank=True, upload_to='static/uploads/%Y/%m/%d/')),
                ('growth_ambitions', models.TextField(blank=True)),
                ('milestones', models.TextField(blank=True)),
                ('do_you_have_audited_books', models.CharField(blank=True, max_length=50)),
                ('total_sales', models.CharField(blank=True, max_length=50)),
                ('total_capital', models.CharField(blank=True, max_length=50)),
                ('expected_capital', models.CharField(blank=True, max_length=50)),
                ('capital_type', models.CharField(blank=True, max_length=50)),
                ('capital_use', models.CharField(blank=True, max_length=50)),
                ('test_plan', models.TextField(blank=True)),
                ('impact_measure_plan', models.TextField(blank=True)),
                ('show_success_plan', models.TextField(blank=True)),
                ('costs', models.TextField(blank=True, max_length=50)),
                ('do_really_well', models.TextField(blank=True)),
                ('key_resources', models.TextField(blank=True)),
                ('key_partners', models.TextField(blank=True)),
                ('problem_change', models.TextField(blank=True)),
                ('customer_change', models.TextField(blank=True)),
                ('planned_acquisition_plan', models.TextField(blank=True)),
                ('performance', models.TextField(blank=True)),
                ('test_learnings', models.TextField(blank=True)),
                ('monthly_cashflow', models.FileField(blank=True, upload_to='static/cashflows/%Y/%m/%d/')),
                ('income_statement', models.FileField(blank=True, upload_to='static/income_statements/%Y/%m/%d/')),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('industry', models.CharField(max_length=255)),
                ('support_stage', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('ticket_size', models.CharField(max_length=20)),
                ('logo', models.FileField(blank=True, upload_to='static/logos/%Y/%m/%d/')),
            ],
        ),
    ]
