# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityhub',
            old_name='preferred_industries',
            new_name='prefered_industries',
        ),
        migrations.RemoveField(
            model_name='investmentcompany',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='investmentcompany',
            name='name',
        ),
        migrations.RemoveField(
            model_name='investmentcompany',
            name='support_stage',
        ),
        migrations.AddField(
            model_name='investmentcompany',
            name='competencies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='investmentcompany',
            name='investment_stage',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='investmentcompany',
            name='investor_focus',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='investmentcompany',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='investmentcompany',
            name='other_industries',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='investmentcompany',
            name='preferred_industries',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='investmentcompany',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentcompany',
            name='specialties',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='investmentcompany',
            name='support_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investmentcompany',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='investmentcompany',
            name='ticket_size',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='investmentcompany',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
