# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170220_0608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityhub',
            old_name='prefered_industries',
            new_name='preferred_industries',
        ),
    ]
