# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_innovation_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovation',
            name='yr_1_projected_earnings',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='innovation',
            name='yr_2_projected_earnings',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='innovation',
            name='yr_3_projected_earnings',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
