# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20170316_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityhub',
            name='logo',
            field=models.FileField(blank=True, upload_to='media/logos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='annual_costs',
            field=models.FileField(blank=True, upload_to='media/uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='income_statement',
            field=models.FileField(blank=True, upload_to='media/income_statements/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/logos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='monthly_cashflow',
            field=models.FileField(blank=True, upload_to='media/cashflows/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='monthly_costs',
            field=models.FileField(blank=True, upload_to='media/uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='service_pic',
            field=models.ImageField(blank=True, upload_to='media/service_pics/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='investmentcompany',
            name='logo',
            field=models.FileField(blank=True, upload_to='media/logos/%Y/%m/%d/'),
        ),
    ]
