# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-27 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_innovation_other_challenges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='service_videos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
