# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 06:53
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20170327_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='annual_costs',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='monthly_costs',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
