# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20170328_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='annual_costs',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='monthly_costs',
            field=models.FileField(upload_to='media'),
        ),
    ]
