# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 08:39
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20170328_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, default='StartupLogo_hqxizg.png', max_length=255, verbose_name='image'),
        ),
    ]
