# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 08:45
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20170328_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='annual_costs',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='monthly_costs',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='raw'),
        ),
    ]
