# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20170328_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='yr_1_projected_earnings',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='yr_2_projected_earnings',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='yr_3_projected_earnings',
            field=models.CharField(max_length=50),
        ),
    ]
