# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20170330_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentcompany',
            name='competencies',
        ),
        migrations.RemoveField(
            model_name='investmentcompany',
            name='description',
        ),
        migrations.RemoveField(
            model_name='investmentcompany',
            name='specialties',
        ),
        migrations.RemoveField(
            model_name='investmentcompany',
            name='support_type',
        ),
    ]
