# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 06:20
from __future__ import unicode_literals

from django.db import migrations
import projects.form_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20170411_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityhub',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='investmentcompany',
            name='lead',
        ),
        migrations.AlterField(
            model_name='innovation',
            name='annual_costs',
            field=projects.form_helpers.CloudinaryField(blank=True, max_length=255, verbose_name='auto'),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='monthly_costs',
            field=projects.form_helpers.CloudinaryField(blank=True, max_length=255, verbose_name='auto'),
        ),
    ]
